language: r
cache: packages

matrix:
  allow_failures:
  - r: devel

  include:
  - r: devel
  - r: release
    r_packages:
    - covr
    r_github_packages:
    - r-lib/pkgdown
    - adatalab/colorhunt
    after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'pkgdown::build_site()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: true
      local-dir: docs
      on:
        branch: master
  - r: release
    os: osx
  - r: oldrel



